env_name              = "banana"
ops_manager_image_uri = "https://opsmanagerimage.blob.local.azurestack.external/images/ops-manager-2.5.4-build.189.vhd"
location              = "local"
dns_suffix            = "local.azurestack.external"
location              = "local"
env_short_name        = "fruit"
